### ISSUE TITLE
New Highlight Blocks

### ISSUE THREAD

**Issue by alanalvarado** [lee-dohm/language-generic-config#10]
Hello, would it be possible to highlight text between [] or {} as some configuration files use it

[DEFAULTS]

also text before and after an = sign like 

sendto = root

**Comment by Alhadis** [comment]
👋  Hey @alanalvarado,

You might find [`language-ini`](https://atom.io/packages/language-ini) better suited for these types of files (with bracketed headings and sections).

The `generic-config` grammar really is supposed to be *generic*... that is, it's not assuming any particular language or format (other than the hash or semicolon-style comment lines, which are very common across many "generic" config files).

**Comment by lee-dohm** [comment]
Thanks for that answer @Alhadis :+1: Totally spot on.
