### ISSUE TITLE
Added some colouring

### ISSUE THREAD

**Issue by Nokel81** [lee-dohm/language-generic-config#14]
I think that it would be great if this also supported some colouring of the config files.

**Examples:**
Here `SomeName` would be one colour and `Option` would be another. Note the space between them.
```
SomeName Option
```

Commas, generally signify separation so they would be still the default colour anyway

**Comment by lee-dohm** [comment]
Thanks for the feedback!

I agree that would be useful for configuration files of a specific structure, such as Git Configuration files. The point of this package though is to have a grammar that assumes the only structure is "comments" and "not comments" to be as generic as possible. I would encourage people to use my package as the basis of their own that provides more functionality for more specific configuration types though :+1:

Thanks again.
